name: Semantic Release

on: push
# on:
#   push:
#     branches:
#       - master

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master

      - uses: codfish/semantic-release-action@master
        id: semanticRelease
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
        with:
          inputs:
            branch: "semantic-release" # todo: tmp


      - run: echo ${{ steps.semanticRelease.outputs.release-version }}
